gimute/KpCup_B_team

GameTemplate/k2EngineLow/FontRender.cpp
GameTemplate/k2EngineLow/FontRender.h
GameTemplate/k2EngineLow/k2EngineLow.vcxproj
GameTemplate/k2EngineLow/k2EngineLow.vcxproj.filters
GameTemplate/k2EngineLow/k2EngineLowPreCompile.h

FontRender追加

---

GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h
GameTemplate/Game/Game.vcxproj
GameTemplate/Game/Game.vcxproj.filters
GameTemplate/Game/GameCamera.cpp
GameTemplate/Game/GameCamera.h
GameTemplate/Game/Player.cpp
GameTemplate/Game/Player.h
GameTemplate/Game/SpeedMeter.cpp
GameTemplate/Game/SpeedMeter.h

プレイヤーのアクセル、ブレーキ、ハンドリング処理作成
カメラの仕様変更
スピードメーター仮実装

Player関連の更新

---

GameTemplate/Game/GameCamera.cpp
GameTemplate/Game/Player.cpp
GameTemplate/Game/Player.h

企画変更による移動プログラムの変更、アニメーション遷移の実装

アニメーション遷移実装、移動変更

---

GameTemplate/Game/Assets/shader/model.fx
GameTemplate/Game/main.cpp
GameTemplate/k2EngineLow/SceneLight.cpp
GameTemplate/k2EngineLow/SceneLight.h
GameTemplate/k2EngineLow/SpotLight.cpp
GameTemplate/k2EngineLow/SpotLight.h
GameTemplate/k2EngineLow/k2EngineLow.vcxproj
GameTemplate/k2EngineLow/k2EngineLow.vcxproj.filters
GameTemplate/k2EngineLow/k2EngineLowPreCompile.h

ライトにスポットライトを追加

---

GameTemplate/Game/main.cpp
GameTemplate/k2EngineLow/CollisionObject.cpp
GameTemplate/k2EngineLow/CollisionObject.h
GameTemplate/k2EngineLow/k2EngineLow.cpp
GameTemplate/k2EngineLow/k2EngineLow.h
GameTemplate/k2EngineLow/k2EngineLow.vcxproj
GameTemplate/k2EngineLow/k2EngineLow.vcxproj.filters
GameTemplate/k2EngineLow/k2EngineLowPreCompile.h

collisionObjectクラス追加

---

GameTemplate/Game/GameCamera.cpp

GameCamera_update

---

GameTemplate/Game/BackGround.cpp
GameTemplate/Game/Enemy.cpp
GameTemplate/Game/Enemy.h
GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h

Enemy_delete

---

GameTemplate/Game/Enemy.cpp
GameTemplate/Game/Enemy.h
GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h

Enemy list

---

GameTemplate/Game/Game.cpp

Enemy_position

---

GameTemplate/Game/Enemy.cpp
GameTemplate/Game/Enemy.h
GameTemplate/Game/EnemyHpUi.cpp
GameTemplate/Game/EnemyHpUi.h
GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h

enemy_Ui_update

---

GameTemplate/Game/Bullet.cpp
GameTemplate/Game/Enemy.cpp
GameTemplate/Game/Player.cpp

弾丸の射手がエネミーかプレイヤーかで判定が取れるようになりました。※当たり判定の名前が違うので注意

弾丸が誰から撃たれたかが区別できるようになった

---

GameTemplate/Game/Enemy.cpp
GameTemplate/Game/Enemy.h
GameTemplate/Game/EnemyAttackPoint.cpp
GameTemplate/Game/EnemyAttackPoint.h
GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h
GameTemplate/Game/Game.vcxproj
GameTemplate/Game/Game.vcxproj.filters

エネミーのコードをある程度人がいじりやすいように変更した、つもり…

Enemy ai 2

---

GameTemplate/Game/Enemy.cpp
GameTemplate/Game/Game.cpp
GameTemplate/Game/GameCamera.cpp
GameTemplate/Game/Player.cpp

ゲームの雑多な変更
プレイヤー
・オート照準の範囲を縮小
・銃撃モードの移動速度を低下
・発砲中も移動可能に変更
・プレイヤーの攻撃モーションのスピードアップ
ゲームカメラ
・回転速度を上昇
その他
・エネミーのHPUIのバグを修正

Game update

---

GameTemplate/Game/Enemy.cpp
GameTemplate/Game/Enemy.h
GameTemplate/Game/EnemyCamPos.cpp
GameTemplate/Game/EnemyCamPos.h
GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h
GameTemplate/Game/Game.vcxproj
GameTemplate/Game/Game.vcxproj.filters
GameTemplate/Game/GameCamera.cpp

エネミーの攻撃頻度を調整するプログラムを実装

---

GameTemplate/Game/Assets/shader/ditheringModel.fx
GameTemplate/Game/BackGround.cpp
GameTemplate/k2EngineLow/ModelRender.cpp
GameTemplate/k2EngineLow/ModelRender.h

ディザリング機能追加

---

GameTemplate/k2EngineLow/LevelRender.cpp
GameTemplate/k2EngineLow/LevelRender.h
GameTemplate/k2EngineLow/k2EngineLow.vcxproj
GameTemplate/k2EngineLow/k2EngineLow.vcxproj.filters
GameTemplate/k2EngineLow/k2EngineLowPreCompile.h

LevelRender追加

---

GameTemplate/Game/Bullet.cpp

プレイヤーが弾を撃つ→エネミーに当たると消える
エネミーが弾を撃つ→プレイヤーに当たると消える

プレイヤーとエネミーの弾の当たり判定調整

---

GameTemplate/Game/Assets/shader/spriteUnder.fx
GameTemplate/Game/Door.cpp
GameTemplate/Game/Door.h

ドアとプレイヤーの衝突判定した時の、アンダーバーの点滅（文字表示）

文字表示のアンダーバーを点滅させた

---

GameTemplate/Game/Assets/shader/spritePinch.fx
GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h

プレイヤーのHPが残り少ない（あと一発食らうとゲームオーバー）時に
赤い点滅と心臓の音を追加した

プレイヤーのHPがピンチの時のエフェクトやSE

---

GameTemplate/Game/Player.cpp
GameTemplate/Game/Player.h

Player update

---

GameTemplate/Game/Game.cpp
GameTemplate/Game/GameTimer.cpp
GameTemplate/Game/Player.cpp
GameTemplate/k2EngineLow/time/GameTime.h

清原先生と話しながら調整した分

---

GameTemplate/Game/Player.cpp
GameTemplate/Game/Player.h

プレイヤーが回避か構えをした際にLスティックを倒していた方向に敵がいた場合そちらを向くように

プレイヤーの構えなどのアシストを改良

---

GameTemplate/Game/Assets/shader/spriteLoad.fx
GameTemplate/Game/BackGround.cpp
GameTemplate/Game/Load.cpp
GameTemplate/Game/Load.h

NowLodingが動いていることを確認するために点滅（明暗）させた。

ロード画面を点滅させた

---

GameTemplate/Game/EnemyCamPos.h
GameTemplate/Game/Game.cpp
GameTemplate/Game/Game.h
GameTemplate/Game/GameClear.cpp
GameTemplate/Game/GameClear.h
GameTemplate/Game/GameTimer.cpp
GameTemplate/Game/GameTimer.h
GameTemplate/Game/InformationUi.cpp
GameTemplate/Game/InformationUi.h
GameTemplate/Game/Player.cpp

game_cppのコメント行がバグっていたので修正。
ゲーム開始時のインフォメーションの処理を修正、動作的には変更なし。
ゲームクリア時のクリアタイムを、GameTimerクラスのオブジェクトを受け取ってクリアタイムを調べる方式から、
ゲームクリア時にGameクラスからクリアタイムを受け取る方式に変更。こちらも動作的には変化なし

Code update
